# Generated by Django 3.0.7 on 2020-06-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_cl', models.CharField(max_length=50)),
                ('Surname_cl', models.CharField(max_length=50)),
                ('Po_batk_cl', models.CharField(max_length=50)),
                ('Seria_passport', models.CharField(max_length=50)),
                ('Nomer_passport', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Diti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bal_ditey', models.FloatField()),
                ('Kilkist_ditey', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dohid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bal_dohodu', models.FloatField()),
                ('Range_dohodu', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Family_stan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bal_stanu', models.FloatField()),
                ('Name_stanu', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Osvita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bal_osviti', models.FloatField()),
                ('Name_osviti', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Posada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bal_posadi', models.FloatField()),
                ('Name_posadi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sfera_roboti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bal_sferi', models.FloatField()),
                ('Name_Sferi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bal_stati', models.FloatField()),
                ('Name_stati', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bal_viku', models.FloatField()),
                ('Vik', models.IntegerField()),
            ],
        ),
    ]
