# Generated by Django 3.0.7 on 2020-06-13 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScoringSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anketa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code_Dohodu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ankets', to='ScoringSystem.Dohid')),
                ('Code_Posadi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ankets', to='ScoringSystem.Posada')),
                ('Code_Sferi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ankets', to='ScoringSystem.Sfera_roboti')),
                ('Code_Stanu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ankets', to='ScoringSystem.Family_stan')),
                ('Code_Stati', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ankets', to='ScoringSystem.Stat')),
                ('Code_Viku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ankets', to='ScoringSystem.Vik')),
                ('Code_ditey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ankets', to='ScoringSystem.Diti')),
                ('Code_osvity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ankets', to='ScoringSystem.Osvita')),
            ],
        ),
    ]
