# Generated by Django 3.0.7 on 2020-06-13 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScoringSystem', '0002_anketa'),
    ]

    operations = [
        migrations.AddField(
            model_name='anketa',
            name='Kod_clienta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ankets', to='ScoringSystem.Client'),
            preserve_default=False,
        ),
    ]
