# Generated by Django 3.0.7 on 2020-06-13 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScoringSystem', '0003_anketa_kod_clienta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bajana_suma_creditu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bal_sumi', models.FloatField()),
                ('Znachennya_creditu', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='anketa',
            name='Code_bajanoi_sumi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ankets', to='ScoringSystem.Bajana_suma_creditu'),
            preserve_default=False,
        ),
    ]
